project:
  type: website
  output-dir: _site

website:
  title: Mt. Vesuvius Lives
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-SU25/final-project-westscotty.git
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Plan of Attack
        href: plan_of_attack.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
      - text: Question 1
        href: project_question_1.qmd
      - text: Question 2
        href: project_question_2.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true


execute:
  freeze: auto
