---
title: "Mt. Vesuvius Lives"
subtitle: "Proposal"
author:
  - name: "Seismic Minds (Cedric Destin, Weston Scott)"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "Exploratory Analysis of Seismic Activity: Mt. Vesuvius"
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
  render-on-save: true
---

| Task ID | Task Name | Status | Due | Priority | Summary |
|------------|------------|------------|------------|------------|------------|
| 1 | Plan out data wrangling methods | Complete | 06/13/2025 | NA | Determine necessary data fields (filters?) Any new data fields (data wrangling - mutate?) |
| 2 | Plan out layer mappings | Complete | 06/13/2025 | NA | Map out the various layers needed for displaying the data for each plots |
| 3 | Plan out functions/packages | Complete | 06/15/2025 | NA | List functions and packages needed for working with said layers |
| 4 | Plan out data mappings to aesthetics | Complete | 06/18/2025 | NA | Map out aesthetic choices (what axes should look like, colors, etc.) |
| 5 | Development question 1 | Complete | 06/21/2025 | NA | Create initial pass at plot 1 |
| 6 | Development question 2 | Complete | 06/21/2025 | NA | Create initial pass at plot 2 |
| 7 | Finalize question 1 | Complete | 06/29/2025 | NA | Create final pass at plot 1 |
| 8 | Finalize question 2 | Complete | 06/28/2025 | NA | Create final pass at plot 2 |
| 9 | Review stage | Complete | 06/30/2025 | NA | Review plots, plan changes |
| 10 | Project summary | In Progress | 06/30/2025 | High | Report development (presentation planning) |
| 11 | Finalize Project | Not Started | 7/01/2025 | High | Put final pieces together, record presentation, and commit final changes |